/**
* Copyright © 2013 Universidad Icesi
* 
* This file is part of SongStock.
* 
* SongStock is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* 
* SongStock is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with SongStock.  If not, see <http://www.gnu.org/licenses/>.
**/
package songstock.web.extensions.login.basic;

import users.dtos.IUser;
import users.dtos.impl.User;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.AbstractErrorMessage.ContentMode;
import com.vaadin.server.ErrorMessage.ErrorLevel;
import com.vaadin.server.UserError;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Notification.Type;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;

/**
 * 
 * @author Andrés Paz
 *
 */
public class BasicLoginForm extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private Label labelError;

	@AutoGenerated
	private Button buttonLogin;

	@AutoGenerated
	private TextField textFieldEmail;

	@AutoGenerated
	private PasswordField passwordField;

	@AutoGenerated
	private Label labelPassword;

	@AutoGenerated
	private Label labelEmail;

	@AutoGenerated
	private Label labelTitle;

	public final static String LOGIN_FORM = "loginForm";
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public BasicLoginForm() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// User code
		
		this.labelError.setValue("");
		this.labelError.setEnabled(false);
		
		this.buttonLogin.addClickListener(new ClickListener() {
			
			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event) {
				doLogin();
			}
		});
	}
	
	protected void doLogin() {
		IUser user = new User();
		String email = textFieldEmail.getValue();
		String password = passwordField.getValue();
		if (!email.equals("")) {
			user.setEmail(email);
			user.setPassword(password);
			BasicLoginFormController.getInstance().doLogin(user);
		}
		else {
			setErrorMessage("Email field cannot be empty.");
		}
	}

	public void setErrorMessage(String message) {
		Notification.show("SongStock", message, Type.TRAY_NOTIFICATION);
		this.labelError.setValue("<i>" + message + "</i>");
		this.buttonLogin.setComponentError(new UserError(message, ContentMode.TEXT, ErrorLevel.WARNING));
	}
	
	public void clear() {
		this.textFieldEmail.setValue("");
		this.passwordField.setValue("");
		this.labelError.setValue("");
		this.buttonLogin.setComponentError(null);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("340px");
		mainLayout.setHeight("180px");
		
		// top-level component properties
		setWidth("340px");
		setHeight("180px");
		
		// labelTitle
		labelTitle = new Label();
		labelTitle.setImmediate(false);
		labelTitle.setWidth("-1px");
		labelTitle.setHeight("-1px");
		labelTitle.setValue("<b>Login Form</b>");
		labelTitle.setContentMode(com.vaadin.shared.ui.label.ContentMode.HTML);
		mainLayout.addComponent(labelTitle, "top:20.0px;left:20.0px;");
		
		// labelEmail
		labelEmail = new Label();
		labelEmail.setImmediate(false);
		labelEmail.setWidth("-1px");
		labelEmail.setHeight("-1px");
		labelEmail.setValue("Email:");
		mainLayout.addComponent(labelEmail, "top:60.0px;left:20.0px;");
		
		// labelPassword
		labelPassword = new Label();
		labelPassword.setImmediate(false);
		labelPassword.setWidth("-1px");
		labelPassword.setHeight("-1px");
		labelPassword.setValue("Password:");
		mainLayout.addComponent(labelPassword, "top:102.0px;left:20.0px;");
		
		// textFieldEmail
		textFieldEmail = new TextField();
		textFieldEmail.setImmediate(false);
		textFieldEmail.setWidth("220px");
		textFieldEmail.setHeight("-1px");
		mainLayout.addComponent(textFieldEmail, "top:60.0px;left:100.0px;");

		// passwordField
		passwordField = new PasswordField();
		passwordField.setImmediate(false);
		passwordField.setWidth("220px");
		passwordField.setHeight("-1px");
		mainLayout.addComponent(passwordField, "top:100.0px;left:100.0px;");
		
		// buttonLogin
		buttonLogin = new Button();
		buttonLogin.setCaption("Login");
		buttonLogin.setImmediate(true);
		buttonLogin.setWidth("61px");
		buttonLogin.setHeight("-1px");
		mainLayout.addComponent(buttonLogin, "top:140.0px;right:19.0px;");
		
		// labelError
		labelError = new Label();
		labelError.setImmediate(false);
		labelError.setWidth("-1px");
		labelError.setHeight("-1px");
		labelError.setValue("<i>Label</i>");
		labelError.setContentMode(com.vaadin.shared.ui.label.ContentMode.HTML);
		mainLayout.addComponent(labelError, "top:142.0px;left:20.0px;");
		
		return mainLayout;
	}

}
